#############################################################################
# Makefile for building: hw8
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Apr 27 16:39:50 2015
# Project:  hw8.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile hw8.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = amazon.cpp \
		book.cpp \
		clothing.cpp \
		datafunction.cpp \
		db_parser.cpp \
		login_window.cpp \
		main_window.cpp \
		movie.cpp \
		product.cpp \
		product_parser.cpp \
		user.cpp \
		util.cpp moc_login_window.cpp \
		moc_main_window.cpp
OBJECTS       = amazon.o \
		book.o \
		clothing.o \
		datafunction.o \
		db_parser.o \
		login_window.o \
		main_window.o \
		movie.o \
		product.o \
		product_parser.o \
		user.o \
		util.o \
		moc_login_window.o \
		moc_main_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hw8.pro
QMAKE_TARGET  = hw8
DESTDIR       = 
TARGET        = hw8

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: hw8.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile hw8.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hw8.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw81.0.0 || $(MKDIR) .tmp/hw81.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw81.0.0/ && $(COPY_FILE) --parents book.h clothing.h datafunction.h datastore.h db_parser.h login_window.h main_window.h movie.h msort.h product.h product_parser.h review.h user.h util.h .tmp/hw81.0.0/ && $(COPY_FILE) --parents amazon.cpp book.cpp clothing.cpp datafunction.cpp db_parser.cpp login_window.cpp main_window.cpp movie.cpp product.cpp product_parser.cpp user.cpp util.cpp .tmp/hw81.0.0/ && (cd `dirname .tmp/hw81.0.0` && $(TAR) hw81.0.0.tar hw81.0.0 && $(COMPRESS) hw81.0.0.tar) && $(MOVE) `dirname .tmp/hw81.0.0`/hw81.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw81.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_login_window.cpp moc_main_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_login_window.cpp moc_main_window.cpp
moc_login_window.cpp: main_window.h \
		product.h \
		review.h \
		datastore.h \
		user.h \
		db_parser.h \
		product_parser.h \
		util.h \
		datafunction.h \
		msort.h \
		login_window.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) login_window.h -o moc_login_window.cpp

moc_main_window.cpp: product.h \
		review.h \
		datastore.h \
		user.h \
		db_parser.h \
		product_parser.h \
		util.h \
		datafunction.h \
		msort.h \
		main_window.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) main_window.h -o moc_main_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

amazon.o: amazon.cpp product.h \
		review.h \
		datastore.h \
		user.h \
		db_parser.h \
		product_parser.h \
		util.h \
		datafunction.h \
		login_window.h \
		main_window.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o amazon.o amazon.cpp

book.o: book.cpp book.h \
		product.h \
		review.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o book.cpp

clothing.o: clothing.cpp clothing.h \
		product.h \
		review.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clothing.o clothing.cpp

datafunction.o: datafunction.cpp datafunction.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		util.h \
		db_parser.h \
		product_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datafunction.o datafunction.cpp

db_parser.o: db_parser.cpp db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_parser.o db_parser.cpp

login_window.o: login_window.cpp login_window.h \
		main_window.h \
		product.h \
		review.h \
		datastore.h \
		user.h \
		db_parser.h \
		product_parser.h \
		util.h \
		datafunction.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login_window.o login_window.cpp

main_window.o: main_window.cpp main_window.h \
		product.h \
		review.h \
		datastore.h \
		user.h \
		db_parser.h \
		product_parser.h \
		util.h \
		datafunction.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o main_window.cpp

movie.o: movie.cpp movie.h \
		product.h \
		review.h \
		util.h \
		book.h \
		clothing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movie.o movie.cpp

product.o: product.cpp product.h \
		review.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product.o product.cpp

product_parser.o: product_parser.cpp product_parser.h \
		product.h \
		review.h \
		book.h \
		util.h \
		clothing.h \
		movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product_parser.o product_parser.cpp

user.o: user.cpp user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

moc_login_window.o: moc_login_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login_window.o moc_login_window.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

